# Generated by Django 3.2.2 on 2021-07-15 07:10

import apps.credentials.models
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Credentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eshop', models.CharField(max_length=128)),
                ('username', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=64)),
                ('token', models.CharField(default=apps.credentials.models._generate_token, max_length=128)),
                ('example_token', models.CharField(blank=True, max_length=128, null=True)),
                ('is_blocked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Доступ',
                'verbose_name_plural': 'Доступы',
            },
        ),
    ]
